name: aviation-budget
channels:
  - conda-forge
dependencies:
  - ipython
  - pandas
  - pymc
  - ipykernel
  - pingouin
  - sympy
  - llvm-openmp>=18
  - libcxx>=19
  - r-base
  - r-tidyverse
  - r-here
  - r-lme4
  - r-emmeans
  - r-performance
  - r-ggplot2
  - r-purrr
  - r-forcats
  - r-tidyr
  - r-dplyr
  - r-stringr
  - r-janitor
  - r-tibble
  - r-colorspace
  - r-patchwork
  - r-matrix
  - r-ggtext
  - r-viridis
  - r-readr
  - r-see
  - r-ggeffects
  - r-ggridges
  - r-rmarkdown
  - r-knitr
  - pip
  - pip:
    - snakemake